- src/main/scala/sbtdynver/DynVerPlugin.scala
> Match on lightweight and containing only major version tags

- README.md
Hi Dale,
Didn't take me long to figure this out, but I thought I'd leave this breadcrumb for future users so they don't get confused about how to get sbt-dynver to recognize tags.
> Update README to specify tag requirements

- README.md
Thank you for a great project! I bumped into this while setting up sbt-dynver in the scalafmt repo, since drone CI clones the repo with `--no-tags` by default.
> Document `git fetch --tags` for CI.

- .travis.yml
- build.sbt
- notes/1.3.0.markdown
- project/CrossBuildingPlugin.scala
- project/build.properties
- project/travis.sh
- src/main/scala/sbtdynver/DynVerPlugin.scala
- src/sbt-test/dynver/custom-version-string-0/build.sbt
- src/sbt-test/dynver/custom-version-string/build.sbt
- src/sbt-test/dynver/versions/build.sbt
> Cross build to sbt 1.0.0-M5

- src/main/scala/sbtdynver/DynVerPlugin.scala
- src/sbt-test/dynver/multi-build/bar/project/plugins.sbt
- src/sbt-test/dynver/multi-build/build.sbt
- src/sbt-test/dynver/multi-build/project/plugins.sbt
- src/sbt-test/dynver/multi-build/test
When using source dependencies with git submodules, one wants the version created by sbt-dynver to be derived from the git submodule instead of the git metadata in the root repository.
This patch makes this work by introducing a `dynverInstance` that is created based on the value of `baseDirectory`.
> Make dynver work with source dependencies

- README.md
- src/main/scala/sbtdynver/DynVerPlugin.scala
- src/sbt-test/dynver/custom-version-string-0/build.sbt
- src/sbt-test/dynver/versions/build.sbt
- src/test/scala/sbtdynver/DynVerSpec.scala
I wanted to fix #53 but you asked for #52 to be fixed first, so this adds a `+0` for dirty snapshots directly after a tag.
In the original bug ticket you say that you also want to add `+0000` but I'm confused by this. There was also the suggestion about adding the commit SHA, too.
Can you elaborate what should be there?
Fixes #52.
> Append +0 to first dirty version after tag

- src/main/scala/sbtdynver/DynVerPlugin.scala
- src/test/scala/sbtdynver/DynVerSpec.scala
- src/test/scala/sbtdynver/RepoStates.scala
It turns out easier than I thought. If it is a snapshot then I append -SNAPSHOT.
This one depends on #63 so probably best to review that first.
Fixes #53.
> Add Sonatype mode

- README.md
- src/main/scala/sbtdynver/DynVerPlugin.scala
- src/test/scala/sbtdynver/DynVerSpec.scala
- src/test/scala/sbtdynver/RepoStates.scala
This command always return the last tagged version before the current HEAD.
Most of the work was done by @MaxwellBo. I just fixed some issues found in usage and cleaned it up slightly. 
- Update SBT cross build version to 1.0.4 and update configs according to SBT crossbuilding guide
When I run `^ mimaReportBinaryIssues` it seems to only run the task for the current SBT version. Manually switching SBT cross build version using `^^ 1.0.4` then `mimaReportBinaryIssues` works fine. Maybe you can spot what I'm doing wrong but this is what I've done for other SBT plugins and it seems to work fine there
> Add support for detecting previous stable version

- src/main/scala/sbtdynver/DynVerPlugin.scala
This, in turn, makes dynverCheckVersion and dynverAssertVersion work.
Fixes #89
> Support dynverSonatypeSnapshots in the dynver task

- src/main/scala/sbtdynver/DynVerPlugin.scala
- src/test/scala/sbtdynver/DynVerSpec.scala
Currently all tags are considered in `git describe` for previous version derivation. However if `git describe` returns non-version tag, it is not parsed successfully and the previous version is None.
This PR makes the `git describe` command consider only tags starting with `v` for previous version derivation.
> Derive previous version when tags are separated with another tag

- README.md
Also try to make the README table fit.
> Document dynverVTagPrefix in the README

- src/test/scala/sbtdynver/JGitSystemReader.scala
- src/test/scala/sbtdynver/RepoStates.scala
I was hitting the following, locally, after recent JGit upgrades (I had
to keep reverting back to 5.5.1.201910021850-r where I wasn't hitting
the issue):
java.nio.file.FileAlreadyExistsException: /Users/dnw/.config
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:94) ~[?:?]
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]
at java.nio.file.Files.createDirectory(Files.java:689) ~[?:?]
at java.nio.file.Files.createAndCheckIsDirectory(Files.java:796) ~[?:?]
at java.nio.file.Files.createDirectories(Files.java:742) ~[?:?]
at …
> Workaround my JGit/symlink issue

- src/test/scala/sbtdynver/RepoStates.scala
I was hitting this:
[info] > Exception: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@35a283ef rejected from java.util.concurrent.ThreadPoolExecutor@630de0e4[Running, pool size = 5, active threads = 5, queued tasks = 0, completed tasks = 0]
[info] java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
[info] java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
[info] java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
[info] java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1714)
[info] java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1931)
[info] …
> Workaround my (new) JGit/FileStore issue

- README.md
which is better, according to https://github.com/lightbend/mima#setting-mimapreviousartifacts-when-name-contains-a-
> Use `moduleName` rather than `name` in mimaPreviousArtifacts

- NOTICE
- README.md
- build.sbt
- sbtdynver/src/main/scala/sbtdynver/DynVerPlugin.scala
- sbtdynver/src/sbt-test/dynver/assert-tag-version/build.sbt
- sbtdynver/src/sbt-test/dynver/custom-version-string-0/build.sbt
- sbtdynver/src/sbt-test/dynver/distance-separator/build.sbt
- sbtdynver/src/sbt-test/dynver/multi-build/build.sbt
- sbtdynver/src/sbt-test/dynver/multi-project/build.sbt
- sbtdynver/src/sbt-test/dynver/no-v-tag-prefix/build.sbt
also bump copyright date and remove redundant license section from readme
> use slash syntax everywhere

- .github/release-drafter.yml
- .github/workflows/ci.yml
- .github/workflows/publish.yml
- .gitignore
- README.md
- build.sbt
- project/build.properties
- project/plugins.sbt
- sbtdynver/src/sbt-test/dynver/assert-tag-version/project/plugins.sbt
- sbtdynver/src/sbt-test/dynver/custom-version-string-0/project/plugins.sbt
- sbtdynver/src/sbt-test/dynver/custom-version-string/project/plugins.sbt
- sbtdynver/src/sbt-test/dynver/distance-separator/project/plugins.sbt
- sbtdynver/src/sbt-test/dynver/multi-build/bar/project/plugins.sbt
- sbtdynver/src/sbt-test/dynver/multi-build/project/plugins.sbt
- sbtdynver/src/sbt-test/dynver/multi-project/project/plugins.sbt
- sbtdynver/src/sbt-test/dynver/no-v-tag-prefix/project/plugins.sbt
- sbtdynver/src/sbt-test/dynver/versions/project/plugins.sbt
This is a continuation of the work done in https://github.com/sbt/sbt-dynver/pull/242 to start publishing with sbt-ci-release.
Closes #239
> feat: start using sbt-ci-release

- .github/release-drafter.yml
- .github/workflows/publish.yml
- .gitignore
- README.md
- build.sbt
- project/build.properties
- project/plugins.sbt
Fixes #239
@SethTisue @eed3si9n please [add secrets](https://github.com/sbt/sbt-ci-release#secrets) and then we can give this a shot. Maybe tagging `v5.0.0-M4` to see if publishing works?
> Use `sbt-ci-release` to publish to `com.github.sbt`

- .github/workflows/ci.yml
- build.sbt
- dynver/src/main/scala/sbtdynver/DynVer.scala
- dynver/src/test/scala/sbtdynver/RepoStates.scala
This builds on top of https://github.com/sbt/sbt-dynver/pull/244, so you'll want to address that one first before looking at this.
The main change here is that it just starts publishing the `dynver` package for 2.13 and 3.
> feat: start cross publishing the dynver package

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- .github/workflows/release-drafter.yml
This will make sure CI runs again on merge as well as release.
> fix(ci): update references of master to main

- build.sbt
- sbtdynver/src/main/scala/sbtdynver/DynVerPlugin.scala
- sbtdynver/src/sbt-test/dynver/assert-tag-version-ok/build.sbt
- sbtdynver/src/sbt-test/dynver/assert-tag-version-ok/changes/build.sbt
- sbtdynver/src/sbt-test/dynver/assert-tag-version-ok/project/plugins.sbt
- sbtdynver/src/sbt-test/dynver/assert-tag-version-ok/test
Fixes https://github.com/sbt/sbt-dynver/issues/254
Ref https://github.com/sbt/sbt-dynver/pull/252 /cc @mkurz 
**Problem**
dynverAssertTagVersion currently throws NPE.
```
[info] [info] Loading settings from plugins.sbt ...
[info] [info] Loading project definition from /.../assert-tag-version-ok/project
[info] [info] Loading settings from build.sbt ...
[info] [error] java.lang.NullPointerException
[info] [error] 	at sbt.internal.util.Init$$anon$11.apply(Settings.scala:690)
[info] [error] 	at sbt.internal.util.Init$$anon$11.apply(Settings.scala:690)
[info] [error] 	at sbt.internal.util.AList$$anon$6.transform(AList.scala:102)
[info] [error] 	at sbt.internal.util.AList$$anon$6.transform(AList.scala:100)
[info] [error] 	at sbt.internal.util.Init$Apply.mapInputs(Settings.scala:837)
[info] …
```
> Fix dynverAssertTagVersion

- README.md
This PR just adds a couple small updates to the existing README.
- Replaces the badge (the one that is there is broken currently)
- Mentions usage of `fetch-depth: 0`, since most users will be using `actions/checkout`
- Mentions the standalone library.
> docs: small updates to the README and mention of the standalone library

- .scala-steward.conf
JGit 6.x requires Java 11, see https://www.eclipse.org/lists/cross-project-issues-dev/msg18654.html
closes: #264 
Reference: https://github.com/scala-steward-org/scala-steward/blob/main/docs/repo-specific-configuration.md?plain=1#L93
> Pin JGit to version 5.*

- build.sbt
I started to block [repo.scala-sbt.org](http://repo.scala-sbt.org/) and [repo.typesafe.com](http://repo.typesafe.com/) in my `/etc/hosts`.
I needed to bump `pluginCrossBuild / sbtVersion` to 1.3.0 so I could fetch all dependencies from maven central.
See
- https://github.com/sbt/sbt/issues/7202
this repo could go down again.
> Bump pluginCrossBuild to sbt 1.3.0, it's on Maven Central

- sbtdynver/src/sbt-test/dynver/assert-tag-version/build.sbt
- sbtdynver/src/sbt-test/dynver/assert-tag-version/test
This test fail if change `pluginCrossBuild / sbtVersion` to 1.10.2 or 2.x.
https://github.com/sbt/sbt-dynver/blob/a3ef1b948827b22e57054316204fb3bebdf8fa94/build.sbt#L64-L66
> fix assert-tag-version test

- .github/workflows/ci.yml
- build.sbt
Snapshot publishing is failing likely due to the overwrite.
This lets sbt-dynver generate the SNAPSHOT version.
> fix: Fix version
